language: node_js
node_js:
  - 12

services:
  - docker  

#Pre-testing installs
install:
  - echo "nothing needs to be installed"

#Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
#Build
  - docker --version #print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
#Tagging
  - docker tag udagram-api-feed mela22/udagram-api-feed:v6
  - docker tag udagram-api-user mela22/udagram-api-user:v6
  - docker tag udagram-frontend mela22/udagram-frontend:v6
  - docker tag reverseproxy mela22/reverseproxy:v6
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mela22/udagram-api-feed:v6
  - docker push mela22/udagram-api-user:v6
  - docker push mela22/udagram-frontend:v6
  - docker push mela22/reverseproxy:v6