language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t mela22/udagram-api-feed:v3 ./udagram-api-feed
  - docker build -t mela22/udagram-api-user:v3 ./udagram-api-user
  - docker build -t mela22/reverseproxy:v3 ./udagram-reverseproxy
  - docker build -t mela22/udagram-frontend:v3 ./udagram-frontend

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mela22/reverseproxy:v3
  - docker push mela22/udagram-api-feed:v3
  - docker push mela22/udagram-api-user:v3
  - docker push mela22/udagram-frontend:v3